language: node_js
node_js:
- 12.18.1
before_install:
- npm install -g npm
script:
- npm install
- npm run start
deploy:
  provider: heroku
  api_key:
    secure: OIhhEf6eciTSmC9u5unHWmiUVE9+lF2fBL26lOSNDZjiMJ0YgrbwVr7gijJA3/2YHtj2gQf4kNwV2MgkQC1LJRVTSTfJUisxmq0CNA25uQh99msi+hkNWDRxz1qRW30fVw6/6lGI+U86AJKV6lElT04gQG6cWLZdrOgQXIOwwyqaZXn6uEjWw3h88dqs9GpCFRtYZa3toTMfYZSJFX/pVM82TnwG5vwzNDRwxw5IzHHbvgx6IMOAd3AXvr0R2pfv9Psghn3QaSyTwmPTqUEEBPSmHE/Rv4z+gJV7o8Rg5H4fS0ldqKMb+5IxxAstPMBKoBKMvd/rAWeDamjPI2LUusZiXl3JCqxEbxiUEb58GG5nHQRk9R0LoN5UkQkS8bWjntjayfybxDw7+cKdJbIYsdnn5O/+CZyGcsj+Ib7jLXW/tmi0KZigVaPFosNlGuNgVyIF1Q/1cdsFEcFP8FnFOUbJbvcvhBLLu2fLXaN1QkJ+UYxxVi7QKR7g7bv8JgYzbtyzEM4+dD7yDJoWY4RLl7nDEo4EfqHjBwQV4dJx3ygqQ4GVSDmYNf/qpvRYloDItfPeC3ubp4y+lSG3NFcAAE+rwhjy8Nnz+OnH/guU9GXfW8cHOcUUjZwGFXFusvkWXT+3sK5w+csxnHkVi2hbzuxmDEFUJLGVndt4kFtIAZk=
  app: cromona
  on:
    repo: GABOdotCODES/cromona
env:
- PORT=3000
  global:
  - secure: hLCnx1VRIaUkp+pJRfD/dzwS5GeHmlXhfU1VNwHTSyQs6qEeD8WU4AQtt1FAk/EIsCSooVDs2ZWHqgMg4ZFv/3dOpnSWLh1DpfRsNImYuWc8gyEJaV0CPa5OWzNad5lJcIkMDf9l7BXeWmrxvM1Fyfk0QJgvqYAEuMGLnHw98oYRlNE4HoTxP8HE54WJhZ7dw9LYfzSAkoq2XUsLXT8KE3KnhlgSNrVnBD/syIUsfAWQt9ZGD+3m04OPLt4TU/xd9tzhmZMjlYaYPe54eqry8WEp1f8SQ5NXZ0V/BXTOdYrdE47xdS4GknTSt8gaQGPcflGznSFzMqudkTXUMM6K2nwqhIM4UbwB55IgPzK1qaxMEOF3KQQkhMpmRXj+By8OiuF1e+1FAu9qtFLsR7b8pGA/DwURvBjqIfDIg8WzZ82hRSAdCr1JmQK+c3BARz5BnvyX+o7HS4/huMbTDSCd9T2ZOixUbSzlzhuRiTawj6vLKkK1o9QLH+xGE0zQaxN1SK+afFVjD4RV3lKcjKtDa3U9ksMDSz4CxKaBpuH1KhVFs8OhsmC6NR0QFiRnbLtJbPjyG2Tj8VWCIdctvX4dThFCAQ6w2fw6D4/tJvBcImHpTeOlBpFMhjwdCdmUrpN7IlDt7DwV9ZUmoGXaa9lt8f/5wih0tpnybWtAAmXRbEU=
  - secure: XqL5BKG9xEx9pWEetdLXRn1aCEB/z9AHL6p4yI7Zo+5Co0ubUV1xfcsgznqxS6jFo5qxLXs1zUEEdMAQqSq/j4NwVzU662Vi8WvGlcWBzGmvUpoO3QkrG2VwvcPu8LELiCoS9ju2QAAC5QOmTBpsY0ThXPpBSHr3mjCdb1zUfe3SGYKbfVr7TGcY8emJ/SWW99V5oLAxZ3ZJx8QbFnuMSoW0ETMY2hekb3Kbtl4nBnYR3RX0zo8rXg+cbBgvp4Zi/Aw72RNGsDro+xViWOVT1Q7ypFBCj2Tffme+pZLTFsrA2bD/u3cX/pZUV29lbpr6cJj6laHPA9Dqer69AtkXYLR6YTJ6Q7NBqhMbU6d4Df8O9oCvcwUYxh7iuYZZZPppQSuWKsWI/lbKF582EOc5FI4By/fn0pAbXBtdPABrxLm0ZXT2cC8gocX1PhjxRZI335eiaulxYMRDtQCkJ4egU3jobID+9lzBu1PnsvMAxIW6xuMBTGpHJC62wxFDRqrSMqL9khtVKzhtq0foxXiXDyGKGXYQeYBrqfazngJPmsu3+Tp/iJNaBgKEezF0fF5IfBl2FSuQkvakUHC2745nAQ1HwiSM3PPOwN84/fA0s2Gh3oH9PXJvE/K3QkyC4THUIrhpgwLK7CsB2jbq2e7VlqPvf+70tygB/6ityQAsqBI=
