language: node_js
node_js:
  - 12.18.1
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: wiYWmcsgxG/xOWpD2h+xk8aExZX3DBTvmc8dugvsxkFc6LrvuzWVupnfZLMEZCHOMiC8zk4wysMcM0eHI3vk9VastonAWFe3fKiUQMmlWsYGvRY4SfkZda+24QuYOuWWr9Vqq13hIpPbJPPZHxb7OuPjJ/f2u6Cc1nj9kpj+V9Tqqe4qmMGTtZwvzvKqo/CY2Lg8QfR2eUCQCJNdl4+aL/FcXBxWsy8DWgohusrdnX/Teq8eP3nk8ZoXH7+7JXJcdgcgCQoNw6A3avgYOIbn7iou9kDwcQleD+sPTNypPHzPF0w6AglGuUmtqK7dSFeaNllWgZ93vfx6BvLH6USi9EDjmDuD93/xJ8b/JuGLH4G9R2L+QW7SQYLxDyuP/uPqeZX495aIx9EZgY55ptsiY6kTxgF6fMBw44AdlbIZpBNUiyYObOzdj9Ke2w2ZHm4JSa0dYVZdkQueX1PCJ8kkBDjYfE0msONAw6gI4hW3kOLq/LFSwdWKVNhPcXB/YDr5gUtKsyP1S0faUBbkW5pn9aPy3RZMENIewWBQqgMWKAwIIv2sKt4BoEwIsBhrqsn2IVGvbwdLHyO5EoR+1XR3gwtGWQ8Ya3crm+hKUsnRN2BLnvfTJBhH8VQu+kQqUwK6lqg7VOE7KPra6pPWa0fataXMsV0RYyoO94q9EFYCdfQ=
  app: cromona
  on:
    repo: GABOdotCODES/cromona
branches:
  only:
    - master
