language: node_js
node_js:
- 12.18.1
before_install:
- npm install -g npm
script:
- npm install
- npm run preset
deploy:
  provider: heroku
  api_key:
    secure: OIhhEf6eciTSmC9u5unHWmiUVE9+lF2fBL26lOSNDZjiMJ0YgrbwVr7gijJA3/2YHtj2gQf4kNwV2MgkQC1LJRVTSTfJUisxmq0CNA25uQh99msi+hkNWDRxz1qRW30fVw6/6lGI+U86AJKV6lElT04gQG6cWLZdrOgQXIOwwyqaZXn6uEjWw3h88dqs9GpCFRtYZa3toTMfYZSJFX/pVM82TnwG5vwzNDRwxw5IzHHbvgx6IMOAd3AXvr0R2pfv9Psghn3QaSyTwmPTqUEEBPSmHE/Rv4z+gJV7o8Rg5H4fS0ldqKMb+5IxxAstPMBKoBKMvd/rAWeDamjPI2LUusZiXl3JCqxEbxiUEb58GG5nHQRk9R0LoN5UkQkS8bWjntjayfybxDw7+cKdJbIYsdnn5O/+CZyGcsj+Ib7jLXW/tmi0KZigVaPFosNlGuNgVyIF1Q/1cdsFEcFP8FnFOUbJbvcvhBLLu2fLXaN1QkJ+UYxxVi7QKR7g7bv8JgYzbtyzEM4+dD7yDJoWY4RLl7nDEo4EfqHjBwQV4dJx3ygqQ4GVSDmYNf/qpvRYloDItfPeC3ubp4y+lSG3NFcAAE+rwhjy8Nnz+OnH/guU9GXfW8cHOcUUjZwGFXFusvkWXT+3sK5w+csxnHkVi2hbzuxmDEFUJLGVndt4kFtIAZk=
  app: cromona
  on:
    repo: GABOdotCODES/cromona